{% set name = "flask-minify" %}
{% set version = "0.48" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-Minify-{{ version }}.tar.gz
  sha256: 0c2e5d6526e6db02d7a05dcdb16da19c21b0cc82f952b0a91adbfca5e4269098

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flask
    - htmlmin
    - jsmin
    - lesscpy
    - python >=3.6
    - rcssmin
    - six
    - python-xxhash

test:
  imports:
    - flask_minify
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mrf345/flask_minify/
  summary: Flask extension to minify html, css, js and less.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - taluripooja
